app/logging/models.py:10: error: Variable "app.logging.models.Base" is not valid as a type  [valid-type]
app/logging/models.py:10: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases
app/logging/models.py:10: error: Invalid base class "Base"  [misc]
app/database.py:23: error: "type" has no attribute "metadata"  [attr-defined]
app/resources/models.py:12: error: Variable "app.database.Base" is not valid as a type  [valid-type]
app/resources/models.py:12: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases
app/resources/models.py:12: error: Invalid base class "Base"  [misc]
app/resources/models.py:21: error: Variable "app.database.Base" is not valid as a type  [valid-type]
app/resources/models.py:21: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases
app/resources/models.py:21: error: Invalid base class "Base"  [misc]
app/resources/models.py:32: error: Variable "app.database.Base" is not valid as a type  [valid-type]
app/resources/models.py:32: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases
app/resources/models.py:32: error: Invalid base class "Base"  [misc]
app/logging/dao.py:97: error: Returning Any from function declared to return "int"  [no-any-return]
app/reporting/dao.py:14: error: Returning Any from function declared to return "int"  [no-any-return]
app/reporting/dao.py:19: error: Returning Any from function declared to return "int"  [no-any-return]
app/reporting/dao.py:24: error: Returning Any from function declared to return "int"  [no-any-return]
app/reporting/dao.py:29: error: Returning Any from function declared to return "int"  [no-any-return]
app/logging/middleware.py:83: error: "Response" has no attribute "body_iterator"  [attr-defined]
app/resources/service.py:80: error: "GenericDAO[User, UserCreate]" has no attribute "get_by_username"  [attr-defined]
app/resources/service.py:87: error: "GenericDAO[User, UserCreate]" has no attribute "get_by_email"; maybe "get_by_id"?  [attr-defined]
app/resources/service.py:108: error: "GenericDAO[User, UserCreate]" has no attribute "get_by_username"  [attr-defined]
app/resources/service.py:116: error: "GenericDAO[User, UserCreate]" has no attribute "get_by_email"; maybe "get_by_id"?  [attr-defined]
app/resources/service.py:130: error: "GenericDAO[User, UserCreate]" has no attribute "get_by_username"  [attr-defined]
app/resources/service.py:133: error: Returning Any from function declared to return "User"  [no-any-return]
app/resources/service.py:149: error: "GenericDAO[Employee, EmployeeCreate]" has no attribute "get_by_employee_id"  [attr-defined]
app/resources/service.py:158: error: "GenericDAO[Employee, EmployeeCreate]" has no attribute "get_by_email"; maybe "get_by_id"?  [attr-defined]
app/resources/service.py:181: error: "GenericDAO[Employee, EmployeeCreate]" has no attribute "get_by_employee_id"  [attr-defined]
app/resources/service.py:191: error: "GenericDAO[Employee, EmployeeCreate]" has no attribute "get_by_email"; maybe "get_by_id"?  [attr-defined]
app/resources/service.py:205: error: Returning Any from function declared to return "list[Employee]"  [no-any-return]
app/resources/service.py:205: error: "GenericDAO[Employee, EmployeeCreate]" has no attribute "get_by_department"  [attr-defined]
app/resources/service.py:209: error: Returning Any from function declared to return "list[Employee]"  [no-any-return]
app/resources/service.py:209: error: "GenericDAO[Employee, EmployeeCreate]" has no attribute "get_by_position"  [attr-defined]
app/resources/service.py:227: error: "GenericDAO[Subscriber, SubscriberCreate]" has no attribute "get_by_email"; maybe "get_by_id"?  [attr-defined]
app/resources/service.py:250: error: "GenericDAO[Subscriber, SubscriberCreate]" has no attribute "get_by_email"; maybe "get_by_id"?  [attr-defined]
app/resources/service.py:264: error: "GenericDAO[Subscriber, SubscriberCreate]" has no attribute "get_by_email"; maybe "get_by_id"?  [attr-defined]
app/resources/service.py:267: error: Returning Any from function declared to return "Subscriber"  [no-any-return]
app/resources/service.py:273: error: Returning Any from function declared to return "list[Subscriber]"  [no-any-return]
app/resources/service.py:273: error: "GenericDAO[Subscriber, SubscriberCreate]" has no attribute "get_by_subscription_tier"  [attr-defined]
app/resources/service.py:277: error: Returning Any from function declared to return "list[Subscriber]"  [no-any-return]
app/resources/service.py:277: error: "GenericDAO[Subscriber, SubscriberCreate]" has no attribute "get_active_subscribers"  [attr-defined]
app/reporting/service.py:104: error: Incompatible default for argument "cycle_code" (default has type "None", argument has type "str")  [assignment]
app/reporting/service.py:104: note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True
app/reporting/service.py:104: note: Use https://github.com/hauntsaninja/no_implicit_optional to automatically upgrade your codebase
app/reporting/service.py:131: error: Value of type "Row | None" is not indexable  [index]
app/reporting/service.py:132: error: Value of type "Row | None" is not indexable  [index]
app/reporting/service.py:133: error: Value of type "Row | None" is not indexable  [index]
app/reporting/service.py:185: error: Returning Any from function declared to return "list[dict[str, str]]"  [no-any-return]
app/resources/registry.py:45: error: Missing positional arguments "model_class", "create_model_class" in call to "GenericService"  [call-arg]
app/reporting/router.py:24: error: "ReportingService" has no attribute "get_recent_activities"  [attr-defined]
app/reporting/router.py:68: error: Argument "cycle_code" to "get_resource_counts" of "ReportingService" has incompatible type "Any | None"; expected "str"  [arg-type]
app/resources/router.py:42: error: Variable "read_model_cls" is not valid as a type  [valid-type]
app/resources/router.py:42: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases
app/resources/router.py:49: error: Item "None" of "ResourceConfig | None" has no attribute "get_service"  [union-attr]
app/resources/router.py:60: error: Item "None" of "ResourceConfig | None" has no attribute "get_service"  [union-attr]
app/resources/router.py:64: error: Item "None" of "ResourceConfig | None" has no attribute "create_model_cls"  [union-attr]
app/resources/router.py:79: error: Item "None" of "ResourceConfig | None" has no attribute "get_service"  [union-attr]
app/resources/router.py:96: error: Item "None" of "ResourceConfig | None" has no attribute "get_service"  [union-attr]
app/resources/router.py:100: error: Item "None" of "ResourceConfig | None" has no attribute "create_model_cls"  [union-attr]
app/resources/router.py:117: error: Item "None" of "ResourceConfig | None" has no attribute "get_service"  [union-attr]
app/resources/router.py:132: error: Item "None" of "ResourceConfig | None" has no attribute "get_service"  [union-attr]
app/resources/router.py:145: error: Item "None" of "ResourceConfig | None" has no attribute "get_service"  [union-attr]
app/resources/router.py:158: error: Item "None" of "ResourceConfig | None" has no attribute "get_service"  [union-attr]
app/resources/router.py:168: error: Item "None" of "ResourceConfig | None" has no attribute "get_service"  [union-attr]
app/resources/router.py:181: error: Item "None" of "ResourceConfig | None" has no attribute "get_service"  [union-attr]
app/resources/router.py:190: error: Item "None" of "ResourceConfig | None" has no attribute "get_service"  [union-attr]
Found 59 errors in 11 files (checked 25 source files)
